import styles from "../styles/Layout.module.css";
import Head from "next/head";
import Image from "next/image";
import { Inter, Poppins } from "next/font/google";
import logo from "../../public/logo.svg";
import boardIcon from "../../public/boardIcon.svg";
import teamIcon from "../../public/teamIcon.svg";
import reportIcon from "../../public/reportIcon.svg";
import adjustIcon from "../../public/adjustIcon.svg";

const font = Inter({ subsets: ["latin"], weight: ["500", "700"] });

const Layout = ({ children }) => (
    <>
        <div className={styles.stripHeader}></div>
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.aside}>
                <Image
                    className={styles.logo}
                    src={logo}
                    width={50}
                    height={56}
                />
                <div className={styles.navigation}>
                    <div className={styles.nav}>
                        <Image
                            src={boardIcon}
                            alt="smartphone icon"
                            width={20}
                            height={20}
                        />
                        <span className={font.className}>Boards</span>
                    </div>
                    <div className={styles.nav}>
                        <Image
                            src={teamIcon}
                            alt="team icon"
                            width={20}
                            height={20}
                        />
                        <span className={font.className}>Equipes</span>
                    </div>
                    <div className={styles.nav}>
                        <Image
                            src={reportIcon}
                            alt="paper icon"
                            width={20}
                            height={20}
                        />
                        <span className={font.className}>Relatórios</span>
                    </div>
                    <div className={styles.nav}>
                        <Image
                            src={adjustIcon}
                            alt="gear icon"
                            width={20}
                            height={20}
                        />
                        <span className={font.className}>Ajustes</span>
                    </div>
                </div>
            </div>
            {children}
        </div>
    </>
);

export default Layout;
